import './global.css'

import {SpeedInsights} from '@vercel/speed-insights/next'
import {Metadata} from 'next'
import Header from './lib/components/Header'

import Footer from './lib/components/Footer'
import {ThemeProvider} from 'next-themes'

export const metadata: Metadata = {
	title: 'Brand Center',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<ThemeProvider>
					<Header />
					<main>{children}</main>
					<Footer />
				</ThemeProvider>
				<SpeedInsights />
			</body>
		</html>
	)
}
