import './global.css'

import {SpeedInsights} from '@vercel/speed-insights/next'
import {Metadata} from 'next'
import Header from './components/Header'
import {Analytics} from '@vercel/analytics/react'
import Footer from './components/Footer'
import {ThemeProvider} from 'next-themes'

export const metadata: Metadata = {
	title: 'Brand Center',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
				<body>
					<ThemeProvider>
						<Header />
						<main>{children}</main>
						<Footer />
					</ThemeProvider>
					<Analytics />
					<SpeedInsights />
				</body>
			</html>
	)
}
